version: '3.8'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file: backend.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 12

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  registration:
    image: gdtkd_reg
    build:
      context: ./frontend
    restart: always
    ports:
      - 80:5000
    volumes:
      - data:/data
    env_file: frontend.env

  processor:
    image: gdtkd_processor
    build:
      context: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - data:/data
    env_file:
      - backend.env

  # debug:
  #   image: gdtkd_processor
  #   entrypoint: ["tail", "-f", "/dev/null"]
  #   build:
  #     context: ./backend
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - data:/data
  #   env_file:
  #     - backend.env

volumes:
  data:
  db:
