flowchart TD
    A([Form]) -->|POST| B(JSON File)
    C(Check for Files)
    C <--> B
    C --> D{File Found?}
    D -->|Yes| E[Write to DB/Sheet]
    D-->|No| F(Sleep)
    E --> C
    F --> C

    subgraph Website
        A
        B
    end                                                           
    subgraph Docker Worker
        direction LR
        C
        D
        E
        F
    end